### ISSUE TITLE
Fix releaser workflows

### ISSUE THREAD

**Issue by agoose77** [agoose77/hatch-nodejs-version#22]
@blink1073 this is a bit cheeky — I can't figure out why the releaser workflow isn't working. The traceback indicates that `GITHUB_TOKEN` isn't set. Do you have any ideas? 

```
Run jupyter-server/jupyter_releaser/.github/actions/prep-release@v2
Run # Install Jupyter Releaser from git unless we are testing Releaser itself
+ command -v jupyter-releaser
+ pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v2
Run export GITHUB_ACCESS_TOKEN= ***
+ export GITHUB_ACCESS_TOKEN= ***
+ GITHUB_ACCESS_TOKEN=
+ export GITHUB_ACTOR=agoose77
+ GITHUB_ACTOR=agoose77
+ export RH_REPOSITORY=
+ RH_REPOSITORY=
+ '[' '!' -z ']'
+ export RH_VERSION_SPEC=next
+ RH_VERSION_SPEC=next
+ export RH_POST_VERSION_SPEC=
+ RH_POST_VERSION_SPEC=
+ export RH_DRY_RUN=false
+ RH_DRY_RUN=false
+ export RH_SINCE=
+ RH_SINCE=
+ export RH_SINCE_LAST_STABLE=true
+ RH_SINCE_LAST_STABLE=true
+ python -m jupyter_releaser.actions.prep_release
Getting GitHub connection for agoose77/hatch-nodejs-version
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ghapi/core.py:102: UserWarning: Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated
  else: warn('Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated')
Getting permission level for agoose77
HTTP Error 401: Unauthorized
====Error Body====
{
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/collaborators/collaborators#get-repository-permissions-for-a-user"
}

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/jupyter_releaser/actions/prep_release.py", line 9, in <module>
    setup(False)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/jupyter_releaser/actions/common.py", line 19, in setup
    return prepare_environment(fetch_draft_release=fetch_draft_release)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/jupyter_releaser/util.py", line 619, in prepare_environment
    raise RuntimeError(msg) from None
RuntimeError: Could not get user permission level, assuming user was not admin!
```

**Comment by blink1073** [comment]
Did you add an `ADMIN_GITHUB_TOKEN` secret on this repo?

**Comment by agoose77** [comment]
Yes, with the same scopes as that used in `jupyterlab-myst` (though it's _not_ the same token).

**Comment by blink1073** [comment]
I'm stumped, I don't understand why it looks like it sets the variable, but then the variable is empty.

Here's what it looks like in [server](https://github.com/jupyter-server/jupyter_server/actions/runs/5898490366/job/15999604669):

```
+ pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v2
Run export GITHUB_ACCESS_TOKEN=***
+ export GITHUB_ACCESS_TOKEN=***
+ GITHUB_ACCESS_TOKEN=***
```

**Comment by agoose77** [comment]
I was stuck too. I recreated the token and re-added the secret, which seems to work. I'm not really sure what happened. Perhaps the token was empty in the secrets ledger, but I really doubt that.
Thanks for taking a look!
